version: '3.8'

# EC2에 사용될 docker-compose
services:
  backend:
    image: junguijin/lpick-backend:latest
    container_name: lpick-backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    volumes:
      - ./API-KEY.yml:/app/API-KEY.yml

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: lpick
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7.2-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  pgdata:
