name: 백엔드 도커 이미지 최신화

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: 백엔드 디렉토리로 이동
        working-directory: ./lpick-backend
        run: echo "Moved to backend directory"

      - name: gradlew 파일에 권한 추가
        working-directory: ./lpick-backend
        run: chmod +x gradlew

      - name: 시크릿에서 API-KEY 가져온 후 생성
        working-directory: ./lpick-backend
        run: |
          mkdir -p src/main/resources
          printf "%s" "${{ secrets.API_KEY_CONTENT }}" > src/main/resources/API-KEY.yml

      - name: Gradle 빌드
        working-directory: ./lpick-backend
        run: ./gradlew clean build

      - name: 도커 허브 로그인
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 빌드 후 DockerHub에 업로드
        working-directory: ./lpick-backend
        run: |
          docker build -t your-dockerhub-username/lpick-backend:latest .
          docker push your-dockerhub-username/lpick-backend:latest
